<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ParkingPro.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ParkingPro.Domain\ParkingPro.Domain.csproj" />
    <ProjectReference Include="..\ParkingPro.Shared\ParkingPro.Shared.csproj" />
  </ItemGroup>

</Project>
